profile:
  store-selected: true
  store-fake-ip: true

dns:
  enable: true
  ipv6: true
  prefer-h3: true
  respect-rules: false
  cache-algorithm: arc
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.msftncsi.com"
    - "+.msftconnecttest.com"
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.dns.sb/dns-query
  direct-nameserver:
    - system
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  direct-nameserver-follow-policy: false
  proxy-server-nameserver:
    - system
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - system
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query

proxies: ~

proxy-groups: ~

rule-providers:
  Direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/Direct.yaml
    interval: 86400

  Proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/Proxy.yaml
    interval: 86400

  Private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/Private.yaml
    interval: 86400

  Telegram_CIDR:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/Telegram_CIDR.yaml
    interval: 86400

  Applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/Applications.yaml
    interval: 86400

  LAN_CIDR:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/LAN_CIDR.yaml
    interval: 86400

  OpenAI:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml"
    path: ./ruleset/OpenAI.yaml
    interval: 86400

  Claude:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude_No_Resolve.yaml"
    path: ./ruleset/Claude.yaml
    interval: 86400

  Bing:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bing/Bing_No_Resolve.yaml"
    path: ./ruleset/Bing.yaml
    interval: 86400

  Copilot:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Copilot/Copilot_No_Resolve.yaml"
    path: ./ruleset/Copilot.yaml
    interval: 86400

  Gemini:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini_No_Resolve.yaml"
    path: ./ruleset/Gemini.yaml
    interval: 86400

  Jetbrains:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Jetbrains/Jetbrains_No_Resolve.yaml"
    path: ./ruleset/Jetbrains.yaml
    interval: 86400

  Developer:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Developer/Developer_No_Resolve.yaml"
    path: ./ruleset/Developer.yaml
    interval: 86400

  Github:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub_No_Resolve.yaml"
    path: ./ruleset/Github.yaml
    interval: 86400

  GoogleFCM:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GoogleFCM/GoogleFCM_No_Resolve.yaml"
    path: ./ruleset/GoogleFCM.yaml
    interval: 86400

  Google:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google_No_Resolve.yaml"
    path: ./ruleset/Google.yaml
    interval: 86400

  OneDrive:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OneDrive/OneDrive_No_Resolve.yaml"
    path: ./ruleset/OneDrive.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft_No_Resolve.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  Game:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game_No_Resolve.yaml"
    path: ./ruleset/Game.yaml
    interval: 86400

  ChinaMedia:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMedia/ChinaMedia_No_Resolve.yaml"
    path: ./ruleset/ChinaMedia.yaml
    interval: 86400

  GlobalMedia:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia_Classical_No_Resolve.yaml"
    path: ./ruleset/GlobalMedia.yaml
    interval: 86400

rules:
  - RULE-SET,Applications,🌀 Direct
  - RULE-SET,LAN_CIDR,🌀 Direct
  - RULE-SET,Private,🌀 Direct
  - RULE-SET,OpenAI,🌑 AI
  - RULE-SET,Claude,🌑 AI
  - RULE-SET,Bing,🌑 AI
  - RULE-SET,Copilot,🌑 AI
  - RULE-SET,Gemini,🌑 AI
  - RULE-SET,Jetbrains,🌑 AI
  - RULE-SET,Developer,🖥 Developer
  - RULE-SET,Github,🖥 Developer
  - RULE-SET,Telegram_CIDR,💬 Telegram,no-resolve
  - RULE-SET,GoogleFCM,🇬 Google
  - RULE-SET,Google,🇬 Google
  - RULE-SET,OneDrive,🪟 Microsoft
  - RULE-SET,Microsoft,🪟 Microsoft
  - RULE-SET,Game,🎮 Game
  - RULE-SET,GlobalMedia,🎥 Media
  - RULE-SET,Proxy,🪀 Proxy
  - RULE-SET,Direct,🌀 Direct
  - GEOIP,CN,🌀 Direct
  - MATCH,🐟 Unmatched
