mode: rule
log-level: info
port: 7899
socks-port: 7898
mixed-port: 7897
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true
external-controller: "127.0.0.1:9097"

geodata-mode: true
geo-auto-update: true
geo-update-interval: 12
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/Country.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country-asn.mmdb"

dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - tls://1.12.12.12:853
    - tls://223.6.6.6:853
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - tls://1.0.0.1:853
    - tls://8.8.4.4:853
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://doh.dns.sb/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.lan"
    - "+.local"
    - "+.msftncsi.com"
    - "+.msftconnecttest.com"
    - "localhost.ptlogin2.qq.com"
    - "localhost.sec.qq.com"
    - "localhost.work.weixin.qq.com"

proxies: ~

proxy-groups: ~

rule-providers:
  p_direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  p_proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  p_reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  p_private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  p_apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  p_icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  p_google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  p_telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  p_lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  p_cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  p_applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  p_OpenAI:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml"
    path: ./ruleset/OpenAI.yaml
    interval: 86400

  p_Claude:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude_No_Resolve.yaml"
    path: ./ruleset/Claude.yaml
    interval: 86400

  p_Bing:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bing/Bing_No_Resolve.yaml"
    path: ./ruleset/Bing.yaml
    interval: 86400

  p_Copilot:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Copilot/Copilot_No_Resolve.yaml"
    path: ./ruleset/Copilot.yaml
    interval: 86400

  p_Gemini:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini_No_Resolve.yaml"
    path: ./ruleset/Gemini.yaml
    interval: 86400

  p_Developer:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Developer/Developer_No_Resolve.yaml"
    path: ./ruleset/Developer.yaml
    interval: 86400

  p_Github:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub_No_Resolve.yaml"
    path: ./ruleset/Github.yaml
    interval: 86400

  p_Jetbrains:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Jetbrains/Jetbrains_No_Resolve.yaml"
    path: ./ruleset/Jetbrains.yaml
    interval: 86400

  p_Microsoft:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft_No_Resolve.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  p_Game:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game_No_Resolve.yaml"
    path: ./ruleset/Game.yaml
    interval: 86400

  p_GameDownload:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/GameDownload/GameDownload_No_Resolve.yaml"
    path: ./ruleset/GameDownload.yaml
    interval: 86400

  p_GlobalMedia:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia_Classical_No_Resolve.yaml"
    path: ./ruleset/GlobalMedia.yaml
    interval: 86400

  p_ChinaMedia:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMedia/ChinaMedia_No_Resolve.yaml"
    path: ./ruleset/ChinaMedia.yaml
    interval: 86400

rules:
  - RULE-SET,p_lancidr,🌀 全球直连
  - RULE-SET,p_applications,🌀 全球直连
  - RULE-SET,p_private,🌀 全球直连
  - RULE-SET,p_reject,📛 禁止通行
  - RULE-SET,p_OpenAI,🌑 Ai
  - RULE-SET,p_Claude,🌑 Ai
  - RULE-SET,p_Bing,🌑 Ai
  - RULE-SET,p_Copilot,🌑 Ai
  - RULE-SET,p_Gemini,🌑 Ai
  - RULE-SET,p_Developer,🖥 Developer
  - RULE-SET,p_Github,🖥 Developer
  - RULE-SET,p_Jetbrains,🖥 Developer
  - RULE-SET,p_telegramcidr,💬 Telegram
  - RULE-SET,p_google,🇬 Google
  - RULE-SET,p_icloud,☁️ iCloud
  - RULE-SET,p_apple,🍎 Apple
  - RULE-SET,p_Microsoft,🪟 微软服务
  - RULE-SET,p_Game,🎮 游戏平台
  - RULE-SET,p_GameDownload,🎮 游戏平台
  - RULE-SET,p_GlobalMedia,🎥 国外媒体
  - RULE-SET,p_ChinaMedia,🎥 国内媒体
  - RULE-SET,p_proxy,🪀 节点选择
  - RULE-SET,p_direct,🌀 全球直连
  - RULE-SET,p_cncidr,🌀 全球直连
  - GEOIP,LAN,🌀 全球直连
  - GEOIP,CN,🌀 全球直连,no-resolve
  - MATCH,🐟 漏网之鱼
