mode: rule
log-level: info
port: 7899
socks-port: 7898
mixed-port: 7897
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true
external-controller: "127.0.0.1:9097"

geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/Country.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country-asn.mmdb"

dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - tls://1.12.12.12:853
    - tls://223.6.6.6:853
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - tls://1.0.0.1:853
    - tls://8.8.4.4:853
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://doh.dns.sb/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.lan"
    - "+.local"
    - "+.msftncsi.com"
    - "+.msftconnecttest.com"
    - "localhost.ptlogin2.qq.com"
    - "localhost.sec.qq.com"
    - "localhost.work.weixin.qq.com"

proxies: ~

proxy-groups: ~

rule-providers:
  Direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/Direct.yaml
    interval: 86400

  Proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/Proxy.yaml
    interval: 86400

  Reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/Reject.yaml
    interval: 86400

  Private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/Private.yaml
    interval: 86400

  Apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/Apple.yaml
    interval: 86400

  iCloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/iCloud.yaml
    interval: 86400

  Telegram_CIDR:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/Telegram_CIDR.yaml
    interval: 86400

  Lan_CIDR:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/Lan_CIDR.yaml
    interval: 86400

  CN_CIDR:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/CN_CIDR.yaml
    interval: 86400

  Applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/Applications.yaml
    interval: 86400

  OpenAI:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml"
    path: ./ruleset/OpenAI.yaml
    interval: 86400

  Claude:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude_No_Resolve.yaml"
    path: ./ruleset/Claude.yaml
    interval: 86400

  Bing:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bing/Bing_No_Resolve.yaml"
    path: ./ruleset/Bing.yaml
    interval: 86400

  Copilot:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Copilot/Copilot_No_Resolve.yaml"
    path: ./ruleset/Copilot.yaml
    interval: 86400

  Gemini:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini_No_Resolve.yaml"
    path: ./ruleset/Gemini.yaml
    interval: 86400

  Developer:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Developer/Developer_No_Resolve.yaml"
    path: ./ruleset/Developer.yaml
    interval: 86400

  Github:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub_No_Resolve.yaml"
    path: ./ruleset/Github.yaml
    interval: 86400

  Jetbrains:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Jetbrains/Jetbrains_No_Resolve.yaml"
    path: ./ruleset/Jetbrains.yaml
    interval: 86400

  GoogleFCM:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GoogleFCM/GoogleFCM_No_Resolve.yaml"
    path: ./ruleset/GoogleFCM.yaml
    interval: 86400

  Google:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google_No_Resolve.yaml"
    path: ./ruleset/Google.yaml
    interval: 86400

  OneDrive:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OneDrive/OneDrive_No_Resolve.yaml"
    path: ./ruleset/OneDrive.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft_No_Resolve.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  Game:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game_No_Resolve.yaml"
    path: ./ruleset/Game.yaml
    interval: 86400

  GameDownload:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/GameDownload/GameDownload_No_Resolve.yaml"
    path: ./ruleset/GameDownload.yaml
    interval: 86400

  GlobalMedia:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia_Classical_No_Resolve.yaml"
    path: ./ruleset/GlobalMedia.yaml
    interval: 86400

  ChinaMedia:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMedia/ChinaMedia_No_Resolve.yaml"
    path: ./ruleset/ChinaMedia.yaml
    interval: 86400

rules:
  - RULE-SET,Lan_CIDR,🌀 全球直连
  - RULE-SET,Applications,🌀 全球直连
  - RULE-SET,Private,🌀 全球直连
  - RULE-SET,Reject,📛 禁止通行
  - RULE-SET,OpenAI,🌑 AI
  - RULE-SET,Claude,🌑 AI
  - RULE-SET,Bing,🌑 AI
  - RULE-SET,Copilot,🌑 AI
  - RULE-SET,Gemini,🌑 AI
  - RULE-SET,Developer,🖥 Developer
  - RULE-SET,Github,🖥 Developer
  - RULE-SET,Jetbrains,🖥 Developer
  - RULE-SET,Telegram_CIDR,💬 Telegram
  - RULE-SET,GoogleFCM,🇬 GoogleFCM
  - RULE-SET,Google,🇬 Google
  - RULE-SET,iCloud,☁️ iCloud
  - RULE-SET,Apple,🍎 Apple
  - RULE-SET,OneDrive,🪟 OneDrive
  - RULE-SET,Microsoft,🪟 Microsoft
  - RULE-SET,Game,🎮 Game
  - RULE-SET,GameDownload,🎮 Game
  - RULE-SET,GlobalMedia,🎥 国外媒体
  - RULE-SET,ChinaMedia,🎥 国内媒体
  - RULE-SET,Proxy,🪀 节点选择
  - RULE-SET,Direct,🌀 全球直连
  - RULE-SET,CN_CIDR,🌀 全球直连
  - GEOIP,LAN,🌀 全球直连,no-resolve
  - GEOIP,CN,🌀 全球直连,no-resolve
  - MATCH,🐟 漏网之鱼
