version = 1

[custom]

enable_rule_generator = true
overwrite_original_rules = false

clash_rule_base = "https://raw.githubusercontent.com/KilluaAoki/Rule-Config/main/Clash_RuleSet/Base.yaml"

[[custom_groups]]
import = "https://raw.githubusercontent.com/KilluaAoki/Rule-Config/main/Clash_RuleSet/Groups.toml"

[[rulesets]]
import = "https://raw.githubusercontent.com/KilluaAoki/Rule-Config/main/Clash_RuleSet/Rulesets.toml"
